### ISSUE TITLE
One to many broadcast?

### ISSUE THREAD

**Issue by lboogs99** [ninjasource/Ninja.WebSockets#11]
Hello all,

I've been looking at this project and it looks pretty stellar. One thing I am not seeing is a broadcast method, is there a method available to do a one to many broadcast? If not, any pointers or tips to build a method around this lib to achieve this?

Thanks!
L

**Comment by devMidgard** [comment]
I'm surprised nobody responded. Anyway this should be fairly easy. Just save each active websocket session into an array, iterate through it and send data to all :)

**Comment by ninjasource** [comment]
Hi L,

My apologies for not getting back to you all these months. This message slipped through the cracks! Like devMidgard said, sending the same message to an array of open web sockets would be the easiest way to do this. Although the websocket protocol is not bound to TCP/IP, it usually runs on top of it and TCP/IP is a point to point protocol. Indeed, when your browser initiates a websocket connection it begins with an HTTP request over TCP/IP.

However, I have run this websocket library over named pipes and other messaging technologies so you could probably use it over UDP (and leverage true broadcast capabilities) if you control both the client and the server.
