### ISSUE TITLE
Websocket ID?

### ISSUE THREAD

**Issue by justStand** [ninjasource/Ninja.WebSockets#12]
When receiving a message from a client as a server, is there any identifier that would tell me which websocket sent the message?

**Comment by ninjasource** [comment]
Hi justStand,

You have two options. You can embed an identifier in path of the http upgrade request. The demo client sets the path to /chat (the full url is wss://thewebsite.com/chat) but you could do something like /chat?id=234556

There is a Path is a property on the WebSocketHttpContext instance you get back when you read the http header using the ReadHttpHeaderFromStreamAsync function of the WebSocketServerFactory. See line 78 of the ProcessTcpClientAsync function in the WebServer class of the DemoServer.

The second option is to use a cookie as an identifier. The cookie would be stored as string in the http header. This header string is also accessible from the WebSocketHttpContext instance. You can use .net libraries to extract the cookie. I suggest you use the built in standard asp.net core websocket functionality if you want to go down this route.

Now, each client gets their own private stream and WebSocket instance so you could wrap the websocket instance in another class that also holds this Id you extracted from the path or cookie. That way when you read from your websocket you also know who it came from.

I hope this helps!

**Comment by justStand** [comment]
I ended up making the _guid field in WebSocketImplementation public. Using a dictionary to map the Guid to a custom id when the connection is opened and another dictionary to map the custom id to the websocket.

Liking the library so far.

**Comment by ninjasource** [comment]
Great! However, I don't know it it is a good idea to expose anything inside the WebSocketImplementation that cannot be found in the WebSocket abstract class. WebSocketImplementation should remain internal and you should pass around a WebSocket instance instead. That way you can replace my library with another one without refactoring your entire project. 

How about something like this:
```
class JustStandWebSocket
{
    WebSocket WebSocket { get; set; }
    Guid Id { get; set; }
}
```
