### ISSUE TITLE
Send message to a specific client

### ISSUE THREAD

**Issue by rsegovia** [ninjasource/Ninja.WebSockets#14]
Hi, I need to developer a function using a WebSocket and send some messages to some specific clients, how can I request a connected websocket client using your library?

In the url I have a "?clientId=12345", i can see it on header and save in a variable, but I dont have idea how search it on the websocket.

Thank you

**Comment by ninjasource** [comment]
Hi, take a look at my response to justStand. You basically create your own class where you save the client ID from the path you have captured along with the WebSocket instance you go when completing the WebSocket handshake. This way you have the flexibility to same as much state as you want about the client.

**Comment by rsegovia** [comment]
I got it, but how i send a message back to the client without a client interation?

Like it, ill have a redis data that another service will save some information there to send to the client, ill get the client id that i need to send information, the information that i need to send and send it. I really cant see how i'll instance that session with client info, thats the point that i need help :(

Thank you

**Comment by rsegovia** [comment]
I think I got it... ill try and will post the result here.

Thank you

**Comment by rsegovia** [comment]
Work!!

something like it
await _clients[0].webSocket.SendAsync(toSend, WebSocketMessageType.Text, true, source.Token);

Thank you :)

**Comment by ninjasource** [comment]
That’s correct! So, if you want to send extra metadata to the client you can always wrap your payload in a json serialisable class that contains the payload AND this extra metadata. If you wanted to formalise this “language” you would use what is called sub-protocol negotiation. Also supported by this library.
