### ISSUE TITLE
What is the advantage of Ninja.WebSockets in comparison to WebSocket implementation from Microsoft?

### ISSUE THREAD

**Issue by msbasanth** [ninjasource/Ninja.WebSockets#15]
Hi,

I am using System.Net.WebSockets.WebSocket in my application and it is having async implementations of SendAsyn and ReceiveAsync. 

Basically used HttpListener and AcceptWebSocketAsync of the context for getting WebSocket instance. Whether we will get additional advantage of using Ninja WebSockets in terms of  performance or usability?

Regards
Basanth

**Comment by eredmo** [comment]
Hi, Basanth

The Microsoft implementation doesn't work on Windows 7 and I've used Ninja.WebSockets successfully to enable that. Thanks to using the same base class the changes needed were minimal. I haven't done any performance benchmarking as such but couldn't notice any difference.

**Comment by trinitrotoluene** [comment]
I believe the windows 7 related WebSocket bugs are patched as of .NET Core 2.1+

2. Juli 2019, 19:47 von notifications@github.com:

**Comment by msbasanth** [comment]
@eredmo Thanks for the explanation. My application is targeting .Net Framework as of now and should run on Windows 7 also.

@trinitrotoluene Thanks for hinting the upates in .Net Core 2.1+.
https://stackoverflow.com/questions/48011763/windows-7-websocket-platformnotsupportedexception
