### ISSUE TITLE
Custom PingPong implementation (server)

### ISSUE THREAD

**Issue by roiko** [ninjasource/Ninja.WebSockets#17]
Hi,
I'm developing a websocket server based on Ninja.WebSockets nuget but I cannot find out how to properly manage the pong message.
There is a client that periodically sends me (the server) a ping request, but, even if I set the KeepAliveInterval option, it does not receive any proper reply. I found the PingPongManager class, but it only offers the Pong event and the SendPing() method... I need the opposite: a Ping event and a SendPong() method.
Is there a way to solve this issue?

Digging a little deeper in your code, I found that a method in WebSocketImplementation class:
`
private async Task SendPongAsync(ArraySegment<byte> payload, CancellationToken cancellationToken)
`

Would it be possible to have it as public?

**Comment by ninjasource** [comment]
Hi Roiko,

You don't have to use the PingPongManager class (or KeepAliveInterval) on the server as this class is used to periodically send ping messages from the Server. The server "should" automatically respond to Ping messages from the client regardless of the PingPongManager or KeepAliveInterval setting. Both clients and servers can send ping messages and expect pong responses and your client appears to be sending a ping message that the server is not responding to as expected. 

Are you running the ReceiveAsync in a loop on its own thread? Take a look at the example server demo. You can use a tool like wireshark to actually see what the server is sending back after getting a Ping message. See line 166 in the ReceiveAsync function of the WebSocketImplementation class. As you can see the server or client always sends a pong in response to a ping. It could also be that the client is sending a Ping message with a payload that is too large. The websocket spec says that the Ping payload cannot be more than 125 bytes.

**Comment by roiko** [comment]
Hi ninja,
thanks for your reply.
Even when using a copy/paste of your sample, I cannot get the server to reply to a ping message.
The error I see is:

`Unexpected end of stream encountered whilst attempting to read 2 bytes`

Do you have any hint?
In the meanwhile, I'll keep investigating the issue

**Comment by roiko** [comment]
Hello again ninja,
I finally understood what the problem was. The client was not waiting enough for the pong message. Because of that, it closed the socket and that's why I got the stream error.
After increasing the ping pong timeout on the client side, the entire mechanism worked like a charm.

Thanks for your support

**Comment by ninjasource** [comment]
Oh that's good, I'm glad you managed to figure it out. You can expect to get that "Unexpected end of stream..." message if the connection is closed by the other party which is what happened in your case.
