### ISSUE TITLE
Is this library support unity webgl platform?

### ISSUE THREAD

**Issue by orangeagain** [ninjasource/Ninja.WebSockets#20]

**Comment by ninjasource** [comment]
Hi, If you are able to open a Stream (of any kind but normally a TcpStream) then you can use this library for WebSocket communication for anything that supports .Net Standard. If you are trying to use this inside a browser (say using the mono .net runtime) then I would first try basic network operations like opening a TCP Stream. Your browser would probably forbid it and you may need some javascript interop. Most browsers support websockets natively so you shouldn't even need this library.

**Comment by orangeagain** [comment]
thank you.
i found a libary support javascript <unitywebsocket>
