### ISSUE TITLE
Ninja.WebSockets.dll is no longer signed with a strong name key

### ISSUE THREAD

**Issue by ryanc1024** [ninjasource/Ninja.WebSockets#21]
I can see that a similar issue was raised previously in #8 which was resolved back in 2018. Looking at the NuGet releases, v1.1.3 was signed with a Strong Name Key (SNK), but the DLL in the subsequent releases is not signed.

Is the intention to provide unsigned libraries through the NuGet release? I would prefer to consume the library as a generic package instead of incorporating it directly into my project solution, but my project must be signed.

ILSpy Data:
v1.0.1.3
// Ninja.WebSockets, Version=1.0.1.3, Culture=neutral, PublicKeyToken=e9d9b92674c8641a
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: v4.0.30319
// This assembly is signed with a strong name key.
// Hash algorithm: SHA1
// Public key: 0024000004800000940000000602000000240000525341310004000001000100b1707056f4761b7846ed503642fcde97fc350c939f78026211304a56ba51e094c9cefde77fadce5b83c0a621c17f032c37c520b6d9ab2da8291a21472175d9caad55bf67bab4bffb46a96f864ea441cf695edc854296e02a44062245a4e09ccd9a77ef6146ecf941ce1d9da078add54bc2d4008decdac2fa2b388e17794ee6a6

v1.0.1.7
// Ninja.WebSockets, Version=1.0.1.7, Culture=neutral, PublicKeyToken=null
// Global type: <Module>
// Architecture: AnyCPU (64-bit preferred)
// Runtime: v4.0.30319
// Hash algorithm: SHA1

**Comment by ninjasource** [comment]
Hi, 

Unfortunately, I have lost the password to the signing key (long story) so, even though I still have a backup of the key, I am unable to use it. That is why I no longer sign the assembly as using a new key can cause all sorts of problems (ask the Log4Net guys about their key signing nightmare). I also really dislike the concept of assembly signing as it gives people a false sense of security, thinking that the source code on github is what they are actually running when it could be anything. If your application requires strong naming then incorporating the source code in your project itself is a good alternative.

**Comment by ryanc1024** [comment]
Understood and thank you for the clarification. The assembly signing is a double-edged sword. We originally leveraged the native implementation for .NET standard, but have encountered some data-in-transit corruption issues with larger data frames (still sorting that out with Microsoft). Since your library implements those abstract classes, it is a drop-in replacement of the native implementation, which is extremely convenient.
