### ISSUE TITLE
Unable to specify correct buffer size for ReceiveAsync

### ISSUE THREAD

**Issue by HeikoBoettger** [ninjasource/Ninja.WebSockets#22]
In the documents of WebSocket.ReceiveAsync it's no where written that the buffer passed to method needs to be as big as the biggest websocket frame expected to be received. Since the receiver as any way no real influence on the frame size chosen by the sender its impossible to set the size correctly. Further WebSocket.ReceiveAsync was designed that the receiver can use smaller buffers than the messages to be able to for example write the received message parts into a file or other stream not requiring to keep all bytes in memory.

I assume the .net core own implementation splits the frames int chunks because I haven't seen the issue there. How can I receive frames bigger than the buffer with ninja?

**Comment by ninjasource** [comment]
Hi, you are absolutely correct, there is no reason why you shouldn’t be able to use a buffer smaller than a websocket frame itself. I have actually implemented that functionality on my other repo embedded-websocket which is a rust implementation. I’m pretty sure I can use the same approach so I’ll see what I can do. Thanks for your post!

**Comment by ninjasource** [comment]
Ok, I have added support for receive buffers smaller than a websocket frame. As long as the receive buffer is big enough to read the websocket header you should be good to go (2-14 bytes depending on client/server and message size). Please test this with the code on the master branch and I will publish a new version to Nuget if that is successful. Thanks again for raising this issue.

**Comment by HeikoBoettger** [comment]
This is awesome. Confirm the version on master works for us, at least our own testcases are green now.

**Comment by ninjasource** [comment]
Glad to help! The nuget package has been published. version 1.1.8
