### ISSUE TITLE
One or more errors occurred. (502 Bad Gateway) while connecting to Azure 

### ISSUE THREAD

**Issue by enniobolondi** [ninjasource/Ninja.WebSockets#23]
Hi, I'm experiencing a 502 error while I'm connecting my ninja ws client to a ws server deployed on Azure.
The error could be easily reproduced by using the "[Ninja.WebSockets.DemoClient](https://github.com/ninjasource/Ninja.WebSockets/tree/master/Ninja.WebSockets.DemoClient)" and try to connect to the following endpoint:
ws://websocketforpyqt.azurewebsites.net

1. Please note that I also tried different ws clients (written in python, javascript, net full framework, net core) and everything worked fine.
2. The web socket server deployed on the azure endpoint is the one you can find on this [github repo](https://github.com/ninjasource/Ninja.WebSockets/tree/master/Ninja.WebSockets.DemoClient). It's written in c# using asp.net 3.1 core framework.
3. If it can help, I can tell you that at the moment I found a (bad) work around: I deployed the ws server on a VM which has a public static IP address. In that way ninja client is able to connect and consume successfully the ws server.

So my conclusion is: seems ninja is not able to resolve the Azure DNS name properly, because seems the cloud normally doesn't work with public ips.
Really appreciate the time you takes to read my post.

Bye
Ennio

**Comment by ninjasource** [comment]
Hi Ennio,

This may happen because the server is rejecting your Origin header. My advice would be to put a breakpoint in the PerformHandshake function of the WebSocketClientFactory class and experiment with the header. Maybe set the Origin to "ws://websocketforpyqt.azurewebsites.net" and the Host to "websocketforpyqt.azurewebsites.net". You can also check the RemoteEndPoint of the stream to see it it has resolved your domain name to an IP address.

Also, try to use wireshark to compare the header generated by your known working clients with this one. A 502 Bad Gateway could be anything but it sounds like your server rejecting an http request because it does not like some header. If it turns out to be the header I can add some code to allow you to override those headers.

One more thing, you probably want to use wss (secure ws) rather than ws.

**Comment by enniobolondi** [comment]
Hi David,
first of all thank you for your reply!
Just a recap: unfortunately I tried the following without success:
1. set the host to "websocketforpyqt.azurewebsites.net" but I received the "host HTTP Error 400. The request has an invalid header name." error (that's fine because I'm forcing the value of a "system header")
2. I set the origin "ws://websocketforpyqt.azurewebsites.net"

I tried to configure CORS on the server side to accept all the headers/origins/methods.
The only good news is that, as you suggested, I captured the traffic using WireShark and (as you can see) a communication is happening between Azure Server (20.50.2.17) and my PC (192.168.1.5), so (I'm quite sure that) **the name has been successfully resolved**.

![immagine](https://user-images.githubusercontent.com/62940832/110313040-30187380-8006-11eb-9207-2ee9d9368a65.png)

It's weird because it:
- can resolve the dns name
- works with a public IP
So why it can't works properly on an azure website?
You told me to experiment a little bit more with headers. Do you have some more idea?
Thank you,
Ennio

PS: yes definitely it's configured to work with wss as well, but I decided to start from the simplies initial condition (no TLS)

**Comment by ninjasource** [comment]
From that screenshot above it looks like it's using TLS (see "Client Hello" line) even though you are using ws (no tls). Try wss. 
For no-tls you can use wireshark to see the actual HTTP header sent to the server. Compare the header sent using my client library with the header sent using your other client libraries that work. Post your entire HTTP headers here and I'll take a look. You can get this string from the PerformHandshake function of the WebSocketClientFactory, assuming that you are working from the source code and not a prebuilt binary.

**Comment by enniobolondi** [comment]
Hi, there are good news!!
I had the Ninja Client works with Azure!! :-)
I need to run more test and be more confident that everything works 100%.

I explain what I did: I added the following option to the "WebSocketClientOptions"
`options.SecWebSocketProtocol = "chat";`
May be this is required by Azure? It's weired because the Net fullframework don't use this field..

Anyway, just because you kindly asked to provide a comparison between "Ninja" and "Net F." clients requests (captured by WireShark):

**NINJA**
```
Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET / HTTP/1.1\r\n]
        Request Method: GET
        Request URI: /
        Request Version: HTTP/1.1
    Host: websocketforpyqt.azurewebsites.net:80\r\n
    Upgrade: websocket\r\n
    Connection: Upgrade\r\n
    Sec-WebSocket-Key: 5QQNC7KYIQA87TwLo+jBtA==\r\n
    Origin: http://websocketforpyqt.azurewebsites.net:80\r\n
    Sec-WebSocket-Protocol: \r\n
    Sec-WebSocket-Version: 13\r\n
    \r\n
    [Full request URI: http://websocketforpyqt.azurewebsites.net:80/]
    [HTTP request 1/1]
    [Response in frame: 21]
```

**NET FULL FRAMEWORK CLIENT**
```
Hypertext Transfer Protocol
    GET / HTTP/1.1\r\n
        [Expert Info (Chat/Sequence): GET / HTTP/1.1\r\n]
        Request Method: GET
        Request URI: /
        Request Version: HTTP/1.1
    Connection: Upgrade,Keep-Alive\r\n
    Upgrade: websocket\r\n
    Sec-WebSocket-Key: v7FWXn13hZWG6+R2P/p8lQ==\r\n
    Sec-WebSocket-Version: 13\r\n
    Host: websocketforpyqt.azurewebsites.net\r\n
    \r\n
    [Full request URI: http://websocketforpyqt.azurewebsites.net/]
    [HTTP request 1/1]
    [Response in frame: 23]
```

If I can have one more day before closing the issue would be great!
And if you need to dive a little deeper and run more checks please tell me how I can help.
Thank you for your help, I really appreciate the time you are putting in this issue.

Bye
Ennio

PS: yes, for the wss it was my fault. Sometimes I run test with TLS enabled.

**Comment by ninjasource** [comment]
Excellent, I'm glad I could help! Thanks for the header snipit and feedback. It's always helpful for other people who will most likely encounter the same issue. 

PS, close the issue whenever you like.

**Comment by enniobolondi** [comment]
Ok I finished my test, the 
`options.SecWebSocketProtocol = "chat";`
made the trick.

Thank you for your help.
I close the issues
