### ISSUE TITLE
Need .Net 4.5 support.

### ISSUE THREAD

**Issue by yingfangdu** [ninjasource/Ninja.WebSockets#5]
Could you please support .Net at least 4.5?
We really want to use this in our project which is target to .Net 4.5 and also run in Xamarin.Mac.

**Comment by ninjasource** [comment]
Sure, I've added support for .net 4.5 (via a project that links the files from the .net standard library) so no duplication of code needed. I've had to tweak one or two things and I'll check it in after I've tested it a little more.

**Comment by ninjasource** [comment]
The .net4.5 package has now been published to Nuget. The same package can be used for both .netstandard 2.0 (so .net 461 and above as well as xamarin and netcore) and .net 4.5

**Comment by yingfangdu** [comment]
thanks very much.
