### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by LeXtruX** [ninjasource/Ninja.WebSockets#6]
I'm having problems figuring out how to use this code...
My biggest issue is that I can't seem to figure out how the DemoServer works. When trying to follow your wiki and build it that way, this is the message I get as soon as I start sending data from the client: WebSocket is already in CLOSING or CLOSED state.
If I use the example I keep getting the blob as a response... 
And I can't figure out how to actually show the data received on the server in the console

**Comment by LeXtruX** [comment]
Update: I figured some bits and pieces out on how this code works, I made the following code to get the text value
`  if (result.MessageType == WebSocketMessageType.Text)
                {
                    string value = Encoding.UTF8.GetString(buffer.Array, 0, result.Count);
                    _logger.LogInformation($"Text received: {value}");
                }`
I assume this is the correct way of doing things?

**Comment by ninjasource** [comment]
Hi, You if you set both the DemoServer and DemoClient as startup projects do they run successfully? It looks like you found some code from the demo client (above).

**Comment by ninjasource** [comment]
No response
