### ISSUE TITLE
Would like to use a custom JSON payload in PingPongManager

### ISSUE THREAD

**Issue by essenbee** [ninjasource/Ninja.WebSockets#7]
I would like to be able to use a custom payload in the PingPongManager. For example, the ping-pong protocol for Slack involves sending the following payload:
```
{
    "id": 1234,
    "type": "ping",
    "time": 1403299273342
}
```
and getting back the following:
```
{
    "reply_to": 1234,
    "type": "pong",
    "time": 1403299273342
}
```
I believe I need to be able to set the payload that gets sent in the private `async Task PingForever()` method, but current cannot see how to do that.

EDIT: A bit more investigation of the code reveals that the Slack ping-pong is not the same as the standard websockets ping-pong, in that it is actually a message exchange of the JSON above, so it looks like I am going to have to write it myself, based off of your excellent netstandard 2.0 library :-)

**Comment by essenbee** [comment]
Rolled my own Pinger class based on your code, and it works great. Many thanks for this library, it made all the difference in my project! I am closing this issue, as it is not relevant to the work you are doing.

**Comment by ninjasource** [comment]
Great, I'm glad you found a way to do that! I wasn't quite sure how to expose ping and pongs cleanly since they left it out of the WebSocket abstract class entirely. It's a little cumbersome at the moment, maybe I should add more examples!
