### ISSUE TITLE
ConnectAsync throws exception when receiving "HTTP/1.1 101 Web Socket Protocol Handshake"

### ISSUE THREAD

**Issue by Flotto85** [ninjasource/Ninja.WebSockets#9]
When the websocket server sends "HTTP/1.1 101 Web Socket Protocol Handshake" instead of "HTTP/1.1 101 Switching Protocols" an exeption is thrown by WebSocketClientFactory.ConnectAsync(...).
The Ninja.Websockets client does not work with the websocket.org echo server.

**Comment by adam-scislowicz** [comment]
This will fix that:

         }
diff --git a/Ninja.WebSockets/WebSocketClientFactory.cs b/Ninja.WebSockets/WebSocketClientFactory.cs
index b60ac58..86b09ef 100644
--- a/Ninja.WebSockets/WebSocketClientFactory.cs
+++ b/Ninja.WebSockets/WebSocketClientFactory.cs
@@ -170,7 +170,7 @@ namespace Ninja.WebSockets
         private void ThrowIfInvalidResponseCode(string responseHeader)
         {
             string responseCode = HttpHelper.ReadHttpResponseCode(responseHeader);
-            if (!string.Equals(responseCode, "101 Switching Protocols", StringComparison.InvariantCultureIgnoreCase))
+            if (!responseCode.StartsWith("101 "))
             {
                 string[] lines = responseHeader.Split(new string[] { "\r\n" }, StringSplitOptions.None);

**Comment by ninjasource** [comment]
Hi Adam,

Thank you for this. I will take a look at your patch and update the codebase and nuget package.

David

**Comment by ZultanH** [comment]
Any updates on this? I am experiencing issues with this as well.

**Comment by ninjasource** [comment]
Ok, I've made a fix for this. Please check the latest version (1.1.7) and see if that fixes it.
